require:
  - rubocop-rails
  - rubocop-graphql

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - db/**/*.rb
